apiVersion: v1
kind: Service
metadata:
   name: msg-api-mp-demo-srv
spec:
   selector:
     app: msg-api-mp-demo
   type: NodePort
   ports:
     - name: http
       port: 9080
       protocol: TCP
       targetPort: 9080

