apiVersion: v1
kind: Service
metadata:
   name: msg-api-mp-demo-srv
spec:
   selector:
     app: msg-api-mp-demo
   type: NodePort
   ports:
     - port: 9081
       protocol: TCP
       targetPort: 9081

