apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-api-mp-demo
  labels:
    app: msg-api-mp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: msg-api-mp-demo
      app.kubernetes.io/instance: msg-api-mp-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: msg-api-mp-demo
        app.kubernetes.io/instance: msg-api-mp-demo
    spec:
      imagePullSecrets:
      containers:
        - name: msg-api-mp-demo
          image: "kiefinger/msg-api-mp-demo:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
          resources:
